const rateActionType = {
  UPDATE_RATE_AFTER_RATING: "UPDATE_RATE_AFTER_RATING",
  FETCH_RATE_START: "FETCH_RATE_START",
  FETCH_RATE_SUCCESS: "FETCH_RATE_SUCCESS",
  FETCH_RATE_FAILURE: "FETCH_RATE_FAILURE",

};
export default rateActionType;
