const EditOption = {
  OPTION_BETWEEN_GROUP_AND_TASK: "OPTION_BETWEEN_GROUP_AND_TASK",
  OPEN_AND_CLOSE_RATE_CARD: "OPEN_AND_CLOSE_RATE_CARD",
  SAVE_RATE_CARD: "SAVE_RATE_CARD",
  AVG_RATE_UPDATED: "AVG_RATE_UPDATED",
  TRIGGER_SEARCH_COMP: "TRIGGER_SEARCH_COMP",
  TRIGGER_SEARCH_ADD_EMPLOYEE: "TRIGGER_SEARCH_ADD_EMPLOYEE",
  
};

export default EditOption;
