const employeeActionTypes = {
  // UPDATE_GROUP: "UPDATE_GROUP",
  FETCH_GROUP_START: "FETCH_GROUP_START",
  FETCH_GROUP_SUCCESS: "FETCH_GROUP_SUCCESS",
  FETCH_GROUP_FAILURE: "FETCH_GROUP_FAILURE",
};

export default employeeActionTypes;
