const searchActionType = {
    ADDING_EMPLOYEE_LIST_TEMP: 'ADDING_EMPLOYEE_LIST_TEMP',
    REMOVING_EMPLOYEE_LIST_TEMP: 'REMOVING_EMPLOYEE_LIST_TEMP',
    CLEAR_EMPLOYEE_LIST_TEMP: 'CLEAR_EMPLOYEE_LIST_TEMP'
  };
  export default searchActionType;
  