const individualsActionType = {
  // UPDATE_EMPLOYEE: "UPDATE_EMPLOYEE",
  // UPDATE_EMPLOYEE_COLLECTIONS: "UPDATE_EMPLOYEE_COLLECTIONS",
  FETCH_EMPLOYEE_START: "FETCH_EMPLOYEE_START",
  FETCH_EMPLOYEE_SUCCESS: "FETCH_EMPLOYEE_SUCCESS",
  FETCH_EMPLOYEE_FAILURE: "FETCH_EMPLOYEE_FAILURE",
  FETCH_EMPLOYEE_ARRAY_START: "FETCH_EMPLOYEE_ARRAY_START",
  FETCH_EMPLOYEE_ARRAY_SUCCESS: "FETCH_EMPLOYEE_ARRAY_SUCCESS",
  FETCH_EMPLOYEE_ARRAY_FAILURE: "FETCH_EMPLOYEE_ARRAY_FAILURE",
};
export default individualsActionType;
